title: Testing Jekyll for documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rbarberop.github.io/jekyll-test

aux_links:
  Template Repository: https://github.com/rbarberop/jekyll-test
